<?php

namespace AppBundle\Repository;

/**
 * CompanySettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanySettingsRepository extends \Doctrine\ORM\EntityRepository
{
}
