<?php

namespace AppBundle\Repository;

/**
 * CurrencyConversionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyConversionRepository extends \Doctrine\ORM\EntityRepository
{
}
