<?php

namespace AppBundle\Repository;

/**
 * OperationLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationLogRepository extends \Doctrine\ORM\EntityRepository
{
}
