<?php

namespace AppBundle\Repository;

/**
 * ProductBrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductBrandRepository extends \Doctrine\ORM\EntityRepository
{
}
