<?php

namespace AppBundle\Repository;

/**
 * ReservationStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
