<?php

namespace AppBundle\Repository;

/**
 * ReservationJoinProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationJoinProductRepository extends \Doctrine\ORM\EntityRepository
{
}
