<?php

namespace AppBundle\Repository;

/**
 * SessionLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionLogRepository extends \Doctrine\ORM\EntityRepository
{
}
