<?php

namespace AppBundle\Repository;

/**
 * VehicleCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehicleCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
