<?php

namespace AppBundle\Repository;

/**
 * VehicleTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehicleTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
