fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

mjmc_crud:
    path: /system/crud/{entityName}/{id}
    controller: MJMC\Bundle\CrudBundle\Controller\CrudController::crudAction
    defaults:
        id: null

app:
    resource: '@AppBundle/Controller/'
    type: annotation
